const BOOK_ACTIONS = {
'ISSUE_BOOK': 'ISSUE_BOOK',
'ISSUE_BOOKS': 'ISSUE_BOOKS',
'TOGGLE_ISSUE_MODAL': 'TOGGLE_ISSUE_MODAL',
'TOGGLE_DELETE_MODAL': 'TOGGLE_DELETE_MODAL',
'DELETE_BOOKS': 'DELETE_BOOKS',
'TOGGLE_RETURN_MODAL': 'TOGGLE_RETURN_MODAL',
'RETURN_BOOKS': 'RETURN_BOOKS',
'SET_BOOKS': 'SET_BOOKS',
'SET_CURRENT_BOOK':'SET_CURRENT_BOOK',
'SET_ISSUE_KEY': 'SET_ISSUE_KEY'
}
export default BOOK_ACTIONS;