const BOOK_ACTIONS = {
'ISSUE_BOOK': 'ISSUE_BOOK',
'ISSUE_BOOKS': 'ISSUE_BOOKS',
'TOGGLE_ISSUE_MODAL': 'TOGGLE_ISSUE_MODAL',
'TOGGLE_DELETE_MODAL': 'TOGGLE_DELETE_MODAL',
'DELETE_BOOKS': 'DELETE_BOOKS',
'SET_BOOKS': 'SET_BOOKS'
}
export default BOOK_ACTIONS;