const ROOT_ACTIONS = {
    TOGGLE_LOGIN_MODAL: "TOGGLE_LOGIN_MODAL",
    LOG_USER_IN:"LOG_USER_IN",
    LOG_USER_OUT: "LOG_USER_OUT",
    TOGGLE_SIDER: "TOGGLE_SIDER",
    UPDATE_USER: "UPDATE_USER",
    TOGGLE_SPINNY: "TOGGLE_SPINNY"
};
export default ROOT_ACTIONS;